### ISSUE TITLE
Support convertEmptyValues

### ISSUE THREAD

**Issue by smtheard** [NerdWalletOSS/dynamorm#57]
Currently if you attempt to set an object with a key and an empty string as the value it will 500 and break. Supporting convertEmptyValues will automatically convert empty strings to nulls so they can be set as 'empty' and not break.

Documentation here: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html

Discussion on the original issue here: https://github.com/aws/aws-sdk-js/issues/833

The quick workaround is to just manually do the conversion obviously, but it would be cool for the orm to support this feature as well.

**Comment by niraj-bpsoftware** [comment]
+1

**Comment by borgstrom** [comment]
We can't support this right now because it's not something that's supported in boto3.   If it were supported in boto3 it would be a fairly easy thing to hookup.

Here's the upstream issue tracking it as a feature request: https://github.com/boto/boto3/issues/1035

When we call boto3 `put_item` all we are providing is a python `dict` from the schema (with the items whose values are `None` removed).

https://github.com/NerdWalletOSS/dynamorm/blob/bd38ca3/dynamorm/table.py#L517-L525

boto3 is inferring the type and forming the query where we would need to transition from `{"S": ""}` to `{"NULL": true}`.  (See the [PutItem API Docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#DDB-PutItem-request-Item)) 

If you really want to store empty strings you could use a custom type and a sentinel null value.  For example, this might look like the following if you used Marshmallow:

```python
class EmptyString(fields.String):
    SENTINEL = '\0'

    def _serialize(self, value, attr, obj):
        res = super(EmptyString, self)._serialize(value, attr, obj)
        return self.SENTINEL if res is None else res

    def _deserialize(self, value, attr, data):
        res = super(EmptyString, self)._deserialize(value, attr, data)
        return '' if res == self.SENTINEL else res
```
